### ISSUE TITLE
the time to write a dask array in tif is too long?

### ISSUE THREAD

**Issue by DeZhao-Zhang** [dymaxionlabs/dask-rasterio#2]
I have a image which have 40000cols and 40000 rows ,while I use data = read_raster(filename, band=1), and the use witer_raster(out_filename, data), it need about one minutes, I want to know can it be quickly

**Comment by munshkr** [comment]
Hi. What is the size of your chunks in your dask array? Have you tried enlarging them? There will always be an overhead compared to writing directly with rasterio, but if your chunks are very small performance will be worse.

**Comment by munshkr** [comment]
I'll close this for now, feel free to reopen if you think there is an issue.
